services:
  javachat-vnc:
    build:
      context: .
      dockerfile: Dockerfile.vnc
    container_name: javachat-vnc
    ports:
      - "5900:5900"    # Puerto VNC
    volumes:
      - .:/root/JavaChat  # Monta tu proyecto en el contenedor
    environment:
      - RESOLUTION=1280x800
      - VNC_PASSWORD=vncpassword
    restart: unless-stopped
